name: Auto-Publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Compile Hugo
      uses: srt32/hugo-action@master
      with:
        args: -D
    - name: Get commit message
      run: echo ::set-env name=COMMIT_MESSAGE::$(git log -1 --pretty=%B)
    - name: Note the file changes
      run: |
        cd $GITHUB_WORKSPACE/public
        git diff --compact-summary
        echo ::set-env name=GIT_DIFF::$(git diff --compact-summary)
    - name: Commit to deployment repo if changes
      run: |
        cd $GITHUB_WORKSPACE
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        cd $GITHUB_WORKSPACE/public
        git diff --compact-summary
        GIT_DIFF=$(git diff --compact-summary)
        if [ -n "$GIT_DIFF" ]; then
          git add -A
          git commit -m "$COMMIT_MESSAGE"
          git push
        fi
